# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Fondling' do

	pod "SOMotionDetector", "~> 1.0.1"
	pod "FontAwesomeKit", "~> 2.1.0"
	pod "JBChartView"

end

target 'FondlingTests' do

end

